import React from "react";

const EDU, DEX;
export const InvestigatorSkills = [
  { name: "威圧", value: 15 },
  { name: "近接戦闘", value: 25 },
  { name: "乗馬", value: 5 },
  { name: "ナビゲート", value: 10 },
  { name: "言いくるめ", value: 5 },
  { name: "信用", value: 0 },
  { name: "変装", value: 5 },
  { name: "医学", value: 1 },
  { name: "心理学", value: 10 },
  { name: "法律", value: 5 },
  { name: "運転(自動車）", value: 20 },
  { name: "クトゥルフ神話", value: 0 },
  { name: "人類学", value: 1 },
  { name: "他言語", value: 1 },
  { name: "応急手当", value: 30 },
  { name: "芸術/製作", value: 5 },
  { name: "水泳", value: 20 },
  { name: "オカルト", value: 5 },
  { name: "精神分析", value: 1 },
  { name: "隠密", value: 20 },
  { name: "説得", value: 10 },
  { name: "母国語", value: EDU },
  { name: "回避", value: DEX / 2 },
  { name: "経理", value: 5 },
  { name: "操縦", value: 1 },
  { name: "魅惑", value: 15 },
  { name: "化学", value: 1 },
  { name: "考古学", value: 1 },
  { name: "跳躍", value: 20 },
  { name: "目星", value: 25 },
  { name: "サバイバル", value: 10 },
  { name: "追跡", value: 10 },
  { name: "歴史", value: 5 },
  { name: "自然", value: 10 },
  { name: "手捌き", value: 10 },
  { name: "鍵開け", value: 1 },
  { name: "射撃(拳銃)", value: 20 },
  { name: "電気修理", value: 10 },
  { name: "鑑定", value: 5 },
  { name: "ライフル/ショットガン", value: 25 },
  { name: "投擲", value: 20 },
  { name: "機械修理", value: 10 },
  { name: "登攀", value: 20 },
  { name: "聞き耳", value: 20 },
  { name: "重機械操作", value: 1 },
  { name: "図書館", value: 20 },
];

export const weapons = [
  { name: "刀", value: 25 },
  { name: "鈍器", value: 25 },
  { name: "ナイフ", value: 25 },
  { name: "拳銃", value: 20 },
  { name: "ボウガン", value: 20 },
  { name: "弓矢", value: 20 },
  { name: "ライフル", value: 25 },
  { name: "ショットガン", value: 25 },
];
